### PR TITLE
Add support for webpack4's plugin API

### PR DESCRIPTION
**Pull request by jdelStrother**
WDYT?

### CODE REVIEW

**Comment by jdelStrother** [comment]
Sure.  Do you have thoughts on what else needs improving?

**Comment by GProst** [comment]
@jdelStrother I think webpack 4 support is the main thing to add.

There was also one unclosed issue about dynamic entry points, but I don't think it's very important. You can help with that if you want 😊

**Comment by GProst** [comment]
@jdelStrother You should receive the invitation to collaborators.

**Comment by jdelStrother** [comment]
I'll see if I can get this merged in this weekend.   Would you like me to update the package on npm as well, or would you rather do that?

**Comment by GProst** [comment]
Added you as a maintainer to npm package 👍

**Pull request merged**
